### PR TITLE
Fix directory reference in shell execution

### PR DESCRIPTION
**Pull request by niklaskors**

### CODE REVIEW

**Comment by niklaskors** [comment]
Merged on #relive.. didn't update base branch before merging

**Review by bWilsher — APPROVED** [review]

**Comment by YousefED** [comment]
do I need to review anything now? Or should we change the PR to #relive branch?

**Comment by niklaskors** [comment]
my bad, my terminal pr workflow doesn't really work with branches 😅

**Comment by niklaskors** [comment]
> do I need to review anything now? Or should we change the PR to #relive branch?

You can ignore this (wrong branch was selected indeed)

**Pull request closed without merging**
